// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Museum.Data;

#nullable disable

namespace Museum.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260221102828_FixedUserModel")]
    partial class FixedUserModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestProj.Models.MuseumEmployeeModel", b =>
                {
                    b.Property<int>("MuseumEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumEmployeeId"));

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MuseumEmployeeId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MuseumEmployees");
                });

            modelBuilder.Entity("TestProj.Models.MuseumImageModel", b =>
                {
                    b.Property<int>("MuseumImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.HasKey("MuseumImageId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumImages");

                    b.HasData(
                        new
                        {
                            MuseumImageId = 1,
                            ImageUrl = "https://api-www.louvre.fr/sites/default/files/2021-01/cour-napoleon-et-pyramide_1.jpg",
                            MuseumId = 1
                        },
                        new
                        {
                            MuseumImageId = 2,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/a/a3/British_Museum_from_NE_2.JPG",
                            MuseumId = 2
                        },
                        new
                        {
                            MuseumImageId = 3,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7c/The_Metropolitan_Museum_of_Art_%28The_Met%29_Logo.svg",
                            MuseumId = 3
                        },
                        new
                        {
                            MuseumImageId = 4,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/6/6f/Vatican_Museums_Entrance.jpg",
                            MuseumId = 4
                        },
                        new
                        {
                            MuseumImageId = 5,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4f/Museo_del_Prado_2016_%28cropped%29.jpg",
                            MuseumId = 5
                        });
                });

            modelBuilder.Entity("TestProj.Models.MuseumModel", b =>
                {
                    b.Property<int>("MuseumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuseumId");

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            MuseumId = 1,
                            Address = "Rue de Rivoli",
                            City = "Paris",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "World's largest art museum.",
                            IsActive = true,
                            Name = "Louvre Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 2,
                            Address = "Great Russell St",
                            City = "London",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Description = "Museum dedicated to human history and culture.",
                            IsActive = true,
                            Name = "British Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 3,
                            Address = "1000 5th Ave",
                            City = "New York",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Largest art museum in the US.",
                            IsActive = true,
                            Name = "Metropolitan Museum of Art",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 4,
                            Address = "Viale Vaticano",
                            City = "Vatican City",
                            ClosingTime = new TimeSpan(0, 16, 0, 0, 0),
                            Description = "Christian and art museums.",
                            IsActive = true,
                            Name = "Vatican Museums",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 5,
                            Address = "Calle de Ruiz de Alarcón",
                            City = "Madrid",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            Description = "Spanish national art museum.",
                            IsActive = true,
                            Name = "Prado Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 6,
                            Address = "Palace Square",
                            City = "Saint Petersburg",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "One of the largest museums in the world.",
                            IsActive = true,
                            Name = "State Hermitage Museum",
                            OpeningTime = new TimeSpan(0, 10, 30, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 7,
                            Address = "Trafalgar Square",
                            City = "London",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Collection of European paintings.",
                            IsActive = true,
                            Name = "National Gallery",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 8,
                            Address = "Museumstraat 1",
                            City = "Amsterdam",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Dutch national museum.",
                            IsActive = true,
                            Name = "Rijksmuseum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 9,
                            Address = "Piazzale degli Uffizi",
                            City = "Florence",
                            ClosingTime = new TimeSpan(0, 18, 30, 0, 0),
                            Description = "Famous Italian art museum.",
                            IsActive = true,
                            Name = "Uffizi Gallery",
                            OpeningTime = new TimeSpan(0, 8, 15, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 10,
                            Address = "Dionysiou Areopagitou 15",
                            City = "Athens",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            Description = "Archaeological museum focused on the Acropolis.",
                            IsActive = true,
                            Name = "Acropolis Museum",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            Type = "Archaeology"
                        },
                        new
                        {
                            MuseumId = 11,
                            Address = "Tahrir Square",
                            City = "Cairo",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Ancient Egyptian antiquities.",
                            IsActive = true,
                            Name = "Egyptian Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 12,
                            Address = "600 Independence Ave SW",
                            City = "Washington",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Description = "Aviation and space artifacts.",
                            IsActive = true,
                            Name = "Smithsonian National Air and Space Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 13,
                            Address = "East Chang'an Avenue",
                            City = "Beijing",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Chinese art and history.",
                            IsActive = true,
                            Name = "National Museum of China",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 14,
                            Address = "13-9 Uenokoen",
                            City = "Tokyo",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Japanese art and antiquities.",
                            IsActive = true,
                            Name = "Tokyo National Museum",
                            OpeningTime = new TimeSpan(0, 9, 30, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 15,
                            Address = "137 Seobinggo-ro",
                            City = "Seoul",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Korean history and art.",
                            IsActive = true,
                            Name = "National Museum of Korea",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 16,
                            Address = "111 S Michigan Ave",
                            City = "Chicago",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Famous art museum in Chicago.",
                            IsActive = true,
                            Name = "Art Institute of Chicago",
                            OpeningTime = new TimeSpan(0, 11, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 17,
                            Address = "11 W 53rd St",
                            City = "New York",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Description = "Modern and contemporary art.",
                            IsActive = true,
                            Name = "Museum of Modern Art",
                            OpeningTime = new TimeSpan(0, 10, 30, 0, 0),
                            Type = "Modern Art"
                        },
                        new
                        {
                            MuseumId = 18,
                            Address = "Museumplein 6",
                            City = "Amsterdam",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Works of Vincent van Gogh.",
                            IsActive = true,
                            Name = "Van Gogh Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 19,
                            Address = "Abandoibarra Etorbidea 2",
                            City = "Bilbao",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Description = "Contemporary art museum.",
                            IsActive = true,
                            Name = "Guggenheim Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Modern Art"
                        },
                        new
                        {
                            MuseumId = 20,
                            Address = "945 Magazine St",
                            City = "New Orleans",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "World War II history.",
                            IsActive = true,
                            Name = "National WWII Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "War"
                        },
                        new
                        {
                            MuseumId = 21,
                            Address = "100 Laurier St",
                            City = "Gatineau",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Canadian history and culture.",
                            IsActive = true,
                            Name = "Canadian Museum of History",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 22,
                            Address = "Av. Paseo de la Reforma",
                            City = "Mexico City",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Description = "Mexican archaeology and anthropology.",
                            IsActive = true,
                            Name = "Museo Nacional de Antropología",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Anthropology"
                        },
                        new
                        {
                            MuseumId = 23,
                            Address = "Bodestraße 1-3",
                            City = "Berlin",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Classical antiquities museum.",
                            IsActive = true,
                            Name = "Pergamon Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Archaeology"
                        },
                        new
                        {
                            MuseumId = 24,
                            Address = "221 Zhishan Rd",
                            City = "Taipei",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Chinese imperial artifacts.",
                            IsActive = true,
                            Name = "National Palace Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 25,
                            Address = "Praça Mauá 1",
                            City = "Rio de Janeiro",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Science museum focused on sustainability.",
                            IsActive = true,
                            Name = "Museum of Tomorrow",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 26,
                            Address = "55 Cable St",
                            City = "Wellington",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Description = "Museum of New Zealand.",
                            IsActive = true,
                            Name = "Te Papa Tongarewa",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 27,
                            Address = "Calle Alfonso XII 68",
                            City = "Madrid",
                            ClosingTime = new TimeSpan(0, 15, 0, 0, 0),
                            Description = "Anthropology museum.",
                            IsActive = true,
                            Name = "National Museum of Anthropology",
                            OpeningTime = new TimeSpan(0, 9, 30, 0, 0),
                            Type = "Anthropology"
                        },
                        new
                        {
                            MuseumId = 28,
                            Address = "500 Harris St",
                            City = "Sydney",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "Science and design museum.",
                            IsActive = true,
                            Name = "Powerhouse Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 29,
                            Address = "Northern Parkway Rd",
                            City = "Johannesburg",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Description = "History of apartheid in South Africa.",
                            IsActive = true,
                            Name = "Apartheid Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 30,
                            Address = "Corniche",
                            City = "Doha",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Description = "Islamic art collection.",
                            IsActive = true,
                            Name = "Museum of Islamic Art",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        });
                });

            modelBuilder.Entity("TestProj.Models.OrderItemModel", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestProj.Models.TicketTypeModel", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("MuseumId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            TicketTypeId = 1,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Adult",
                            Price = 25m
                        },
                        new
                        {
                            TicketTypeId = 2,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Student",
                            Price = 15m
                        },
                        new
                        {
                            TicketTypeId = 3,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Child",
                            Price = 10m
                        },
                        new
                        {
                            TicketTypeId = 4,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 5,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 6,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 7,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Adult",
                            Price = 28m
                        },
                        new
                        {
                            TicketTypeId = 8,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Student",
                            Price = 18m
                        },
                        new
                        {
                            TicketTypeId = 9,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Child",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 10,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Adult",
                            Price = 30m
                        },
                        new
                        {
                            TicketTypeId = 11,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Student",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 12,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Child",
                            Price = 15m
                        },
                        new
                        {
                            TicketTypeId = 13,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Adult",
                            Price = 22m
                        },
                        new
                        {
                            TicketTypeId = 14,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Student",
                            Price = 14m
                        },
                        new
                        {
                            TicketTypeId = 15,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Child",
                            Price = 9m
                        },
                        new
                        {
                            TicketTypeId = 16,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 17,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 18,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 19,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 20,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 21,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 22,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 23,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 24,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 25,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 26,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 27,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 28,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 29,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 30,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 31,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 32,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 33,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 34,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 35,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 36,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 37,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 38,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 39,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 40,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 41,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 42,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 43,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 44,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 45,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 46,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 47,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 48,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 49,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 50,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 51,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 52,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 53,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 54,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 55,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 56,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 57,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 58,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 59,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 60,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 61,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 62,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 63,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 64,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 65,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 66,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 67,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 68,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 69,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 70,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 71,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 72,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 73,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 74,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 75,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 76,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 77,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 78,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 79,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 80,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 81,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 82,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 83,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 84,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 85,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 86,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 87,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 88,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 89,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 90,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Child",
                            Price = 8m
                        });
                });

            modelBuilder.Entity("TestProj.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProj.Models.MuseumEmployeeModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Employees")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", "User")
                        .WithOne("MuseumEmployee")
                        .HasForeignKey("TestProj.Models.MuseumEmployeeModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestProj.Models.MuseumImageModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Images")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("TestProj.Models.OrderItemModel", b =>
                {
                    b.HasOne("TestProj.Models.OrderModel", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.TicketTypeModel", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Orders")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestProj.Models.TicketTypeModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("TicketTypes")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("TestProj.Models.MuseumModel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Images");

                    b.Navigation("Orders");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TestProj.Models.UserModel", b =>
                {
                    b.Navigation("MuseumEmployee")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
