// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestProj.Data;

#nullable disable

namespace TestProj.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260312093222_SeededDefaultMuseumsImages")]
    partial class SeededDefaultMuseumsImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestProj.Models.MuseumEmployeeModel", b =>
                {
                    b.Property<int>("MuseumEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumEmployeeId"));

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MuseumEmployeeId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("MuseumEmployees");
                });

            modelBuilder.Entity("TestProj.Models.MuseumImageModel", b =>
                {
                    b.Property<int>("MuseumImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.HasKey("MuseumImageId");

                    b.HasIndex("MuseumId");

                    b.ToTable("MuseumImages");

                    b.HasData(
                        new
                        {
                            MuseumImageId = 1,
                            ImageUrl = "https://t4.ftcdn.net/jpg/03/02/03/03/240_F_302030306_VLGXUtPa0QId7O6Zqz9AF6RSql6uIdVd.jpg",
                            MuseumId = 1
                        },
                        new
                        {
                            MuseumImageId = 2,
                            ImageUrl = "https://t3.ftcdn.net/jpg/00/95/44/26/240_F_95442619_GrhmvQcSput2G9lrbG8QRzX96H3MAvlG.jpg",
                            MuseumId = 2
                        },
                        new
                        {
                            MuseumImageId = 3,
                            ImageUrl = "https://t3.ftcdn.net/jpg/06/66/26/00/240_F_666260007_eCaT4Pk5BP9zWzvY5wPQRjRdLLlkLkVe.jpg",
                            MuseumId = 3
                        },
                        new
                        {
                            MuseumImageId = 4,
                            ImageUrl = "https://t3.ftcdn.net/jpg/05/07/06/78/240_F_507067856_oeG1oQO9FyZhA7j0e0IpTHwsS3ZVWtln.jpg",
                            MuseumId = 4
                        },
                        new
                        {
                            MuseumImageId = 5,
                            ImageUrl = "https://t4.ftcdn.net/jpg/00/83/91/39/240_F_83913965_MdPt8k5xeVa4sIx0zuajUTGGtpqQijkv.jpg",
                            MuseumId = 5
                        },
                        new
                        {
                            MuseumImageId = 6,
                            ImageUrl = "https://t3.ftcdn.net/jpg/18/33/81/44/240_F_1833814465_cDXO5nqwcDp4W9EMiY3eRVkL5zhhQlzJ.jpg",
                            MuseumId = 6
                        },
                        new
                        {
                            MuseumImageId = 7,
                            ImageUrl = "https://t3.ftcdn.net/jpg/02/67/14/66/240_F_267146668_0k2G3hX2Vf9YJ7bA8nXgR0r0nE5K3F8K.jpg",
                            MuseumId = 7
                        },
                        new
                        {
                            MuseumImageId = 8,
                            ImageUrl = "https://t4.ftcdn.net/jpg/01/84/22/97/240_F_184229782_yN0kqzP6n3d6XnL3qQqZpM3u6EJr3K8Q.jpg",
                            MuseumId = 8
                        },
                        new
                        {
                            MuseumImageId = 9,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/21/44/56/240_F_321445673_jJrF1d8Jm5sF7vM1bT0Xc6yL8q9p6n2.jpg",
                            MuseumId = 9
                        },
                        new
                        {
                            MuseumImageId = 10,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/94/71/31/240_F_294713180_Zy2VqzE1b1TQn4bS3c0lJ5Fh1Tn8xA0.jpg",
                            MuseumId = 10
                        },
                        new
                        {
                            MuseumImageId = 11,
                            ImageUrl = "https://t3.ftcdn.net/jpg/02/15/32/77/240_F_215327715_qYdE5YjL5r5E9pG3z6H2zY5E1X7p4mK.jpg",
                            MuseumId = 11
                        },
                        new
                        {
                            MuseumImageId = 12,
                            ImageUrl = "https://t4.ftcdn.net/jpg/03/12/64/09/240_F_312640987_T6n4gZ9Y5Yk3Yh2F5X5pY0z1C7d8x9.jpg",
                            MuseumId = 12
                        },
                        new
                        {
                            MuseumImageId = 13,
                            ImageUrl = "https://t3.ftcdn.net/jpg/01/97/23/88/240_F_197238884_kJ0P8Y7V8q7X2H2P5m2N4L1c5y3b8k.jpg",
                            MuseumId = 13
                        },
                        new
                        {
                            MuseumImageId = 14,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/53/11/90/240_F_253119063_L2o2K5y2M8z3L8c8R3P2F6d2B1y8z.jpg",
                            MuseumId = 14
                        },
                        new
                        {
                            MuseumImageId = 15,
                            ImageUrl = "https://t3.ftcdn.net/jpg/04/20/77/91/240_F_420779188_m6r8X5Y3H4L3B2Y4m5p7Z9Q1A4Y2x.jpg",
                            MuseumId = 15
                        },
                        new
                        {
                            MuseumImageId = 16,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/18/74/53/240_F_218745357_x6P3k3F3G2F8m2P6q5J4T8Y5z1n2.jpg",
                            MuseumId = 16
                        },
                        new
                        {
                            MuseumImageId = 17,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/30/77/45/240_F_330774560_Xc1y6P6X3x9H1P5m2Q4F8z5Z3y1.jpg",
                            MuseumId = 17
                        },
                        new
                        {
                            MuseumImageId = 18,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/88/61/55/240_F_288615596_gY1M1Z7b3X6F5Z9p8T2P7L3Q6F3.jpg",
                            MuseumId = 18
                        },
                        new
                        {
                            MuseumImageId = 19,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/64/70/02/240_F_364700229_bX1F4m2X4Q6n5T3p6L8Z3P4L7.jpg",
                            MuseumId = 19
                        },
                        new
                        {
                            MuseumImageId = 20,
                            ImageUrl = "https://t4.ftcdn.net/jpg/03/45/98/55/240_F_345985574_X3p5X3M7F2K3P7X4L3m6F5Z1.jpg",
                            MuseumId = 20
                        },
                        new
                        {
                            MuseumImageId = 21,
                            ImageUrl = "https://t3.ftcdn.net/jpg/02/76/44/11/240_F_276441156_T1y7Y5M3F8X4P9M4Z6X1p3Z.jpg",
                            MuseumId = 21
                        },
                        new
                        {
                            MuseumImageId = 22,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/33/88/90/240_F_233889006_K5Y3Z8Q4F7M2Z5L7F6Q3T2.jpg",
                            MuseumId = 22
                        },
                        new
                        {
                            MuseumImageId = 23,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/10/75/66/240_F_310756652_L1T4M6P9Z4F2L5P7Y6K3.jpg",
                            MuseumId = 23
                        },
                        new
                        {
                            MuseumImageId = 24,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/64/88/23/240_F_264882381_H4P7M5Z6F3L8Q3P7X5.jpg",
                            MuseumId = 24
                        },
                        new
                        {
                            MuseumImageId = 25,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/91/00/14/240_F_391001462_T3P8Z7F4M5X3L8Y1.jpg",
                            MuseumId = 25
                        },
                        new
                        {
                            MuseumImageId = 26,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/55/63/12/240_F_255631245_M5X4L6T2Z8P5.jpg",
                            MuseumId = 26
                        },
                        new
                        {
                            MuseumImageId = 27,
                            ImageUrl = "https://t3.ftcdn.net/jpg/02/99/55/18/240_F_299551862_Y5M6Z8X4P3F1.jpg",
                            MuseumId = 27
                        },
                        new
                        {
                            MuseumImageId = 28,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/71/33/66/240_F_271336631_Z4P6L2F9M3.jpg",
                            MuseumId = 28
                        },
                        new
                        {
                            MuseumImageId = 29,
                            ImageUrl = "https://t3.ftcdn.net/jpg/03/40/19/87/240_F_340198709_Q4M8F5Z2P6.jpg",
                            MuseumId = 29
                        },
                        new
                        {
                            MuseumImageId = 30,
                            ImageUrl = "https://t4.ftcdn.net/jpg/02/90/77/44/240_F_290774463_M6X2P8L5F3.jpg",
                            MuseumId = 30
                        });
                });

            modelBuilder.Entity("TestProj.Models.MuseumModel", b =>
                {
                    b.Property<int>("MuseumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MuseumId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MuseumId");

                    b.ToTable("Museums");

                    b.HasData(
                        new
                        {
                            MuseumId = 1,
                            Address = "Rue de Rivoli",
                            City = "Paris",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "France",
                            Description = "World's largest art museum.",
                            IsActive = true,
                            Name = "Louvre Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 2,
                            Address = "Great Russell St",
                            City = "London",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Country = "United Kingdom",
                            Description = "Museum dedicated to human history and culture.",
                            IsActive = true,
                            Name = "British Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 3,
                            Address = "1000 5th Ave",
                            City = "New York",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "USA",
                            Description = "Largest art museum in the US.",
                            IsActive = true,
                            Name = "Metropolitan Museum of Art",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 4,
                            Address = "Viale Vaticano",
                            City = "Vatican City",
                            ClosingTime = new TimeSpan(0, 16, 0, 0, 0),
                            Country = "Vatican City",
                            Description = "Christian and art museums.",
                            IsActive = true,
                            Name = "Vatican Museums",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 5,
                            Address = "Calle de Ruiz de Alarcón",
                            City = "Madrid",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            Country = "Spain",
                            Description = "Spanish national art museum.",
                            IsActive = true,
                            Name = "Prado Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 6,
                            Address = "Palace Square",
                            City = "Saint Petersburg",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "Russia",
                            Description = "One of the largest museums in the world.",
                            IsActive = true,
                            Name = "State Hermitage Museum",
                            OpeningTime = new TimeSpan(0, 10, 30, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 7,
                            Address = "Trafalgar Square",
                            City = "London",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "United Kingdom",
                            Description = "Collection of European paintings.",
                            IsActive = true,
                            Name = "National Gallery",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 8,
                            Address = "Museumstraat 1",
                            City = "Amsterdam",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Netherlands",
                            Description = "Dutch national museum.",
                            IsActive = true,
                            Name = "Rijksmuseum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 9,
                            Address = "Piazzale degli Uffizi",
                            City = "Florence",
                            ClosingTime = new TimeSpan(0, 18, 30, 0, 0),
                            Country = "Italy",
                            Description = "Famous Italian art museum.",
                            IsActive = true,
                            Name = "Uffizi Gallery",
                            OpeningTime = new TimeSpan(0, 8, 15, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 10,
                            Address = "Dionysiou Areopagitou 15",
                            City = "Athens",
                            ClosingTime = new TimeSpan(0, 20, 0, 0, 0),
                            Country = "Greece",
                            Description = "Archaeological museum focused on the Acropolis.",
                            IsActive = true,
                            Name = "Acropolis Museum",
                            OpeningTime = new TimeSpan(0, 8, 0, 0, 0),
                            Type = "Archaeology"
                        },
                        new
                        {
                            MuseumId = 11,
                            Address = "Tahrir Square",
                            City = "Cairo",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Egypt",
                            Description = "Ancient Egyptian antiquities.",
                            IsActive = true,
                            Name = "Egyptian Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 12,
                            Address = "600 Independence Ave SW",
                            City = "Washington",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Country = "USA",
                            Description = "Aviation and space artifacts.",
                            IsActive = true,
                            Name = "Smithsonian National Air and Space Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 13,
                            Address = "East Chang'an Avenue",
                            City = "Beijing",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "China",
                            Description = "Chinese art and history.",
                            IsActive = true,
                            Name = "National Museum of China",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 14,
                            Address = "13-9 Uenokoen",
                            City = "Tokyo",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Japan",
                            Description = "Japanese art and antiquities.",
                            IsActive = true,
                            Name = "Tokyo National Museum",
                            OpeningTime = new TimeSpan(0, 9, 30, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 15,
                            Address = "137 Seobinggo-ro",
                            City = "Seoul",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "South Korea",
                            Description = "Korean history and art.",
                            IsActive = true,
                            Name = "National Museum of Korea",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 16,
                            Address = "111 S Michigan Ave",
                            City = "Chicago",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "USA",
                            Description = "Famous art museum in Chicago.",
                            IsActive = true,
                            Name = "Art Institute of Chicago",
                            OpeningTime = new TimeSpan(0, 11, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 17,
                            Address = "11 W 53rd St",
                            City = "New York",
                            ClosingTime = new TimeSpan(0, 17, 30, 0, 0),
                            Country = "USA",
                            Description = "Modern and contemporary art.",
                            IsActive = true,
                            Name = "Museum of Modern Art",
                            OpeningTime = new TimeSpan(0, 10, 30, 0, 0),
                            Type = "Modern Art"
                        },
                        new
                        {
                            MuseumId = 18,
                            Address = "Museumplein 6",
                            City = "Amsterdam",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "Netherlands",
                            Description = "Works of Vincent van Gogh.",
                            IsActive = true,
                            Name = "Van Gogh Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        },
                        new
                        {
                            MuseumId = 19,
                            Address = "Abandoibarra Etorbidea 2",
                            City = "Bilbao",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Country = "Spain",
                            Description = "Contemporary art museum.",
                            IsActive = true,
                            Name = "Guggenheim Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Modern Art"
                        },
                        new
                        {
                            MuseumId = 20,
                            Address = "945 Magazine St",
                            City = "New Orleans",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "USA",
                            Description = "World War II history.",
                            IsActive = true,
                            Name = "National WWII Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "War"
                        },
                        new
                        {
                            MuseumId = 21,
                            Address = "100 Laurier St",
                            City = "Gatineau",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Canada",
                            Description = "Canadian history and culture.",
                            IsActive = true,
                            Name = "Canadian Museum of History",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 22,
                            Address = "Av. Paseo de la Reforma",
                            City = "Mexico City",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Country = "Mexico",
                            Description = "Mexican archaeology and anthropology.",
                            IsActive = true,
                            Name = "Museo Nacional de Antropología",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Anthropology"
                        },
                        new
                        {
                            MuseumId = 23,
                            Address = "Bodestraße 1-3",
                            City = "Berlin",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "Germany",
                            Description = "Classical antiquities museum.",
                            IsActive = true,
                            Name = "Pergamon Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Archaeology"
                        },
                        new
                        {
                            MuseumId = 24,
                            Address = "221 Zhishan Rd",
                            City = "Taipei",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Taiwan",
                            Description = "Chinese imperial artifacts.",
                            IsActive = true,
                            Name = "National Palace Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 25,
                            Address = "Praça Mauá 1",
                            City = "Rio de Janeiro",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "Brazil",
                            Description = "Science museum focused on sustainability.",
                            IsActive = true,
                            Name = "Museum of Tomorrow",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 26,
                            Address = "55 Cable St",
                            City = "Wellington",
                            ClosingTime = new TimeSpan(0, 18, 0, 0, 0),
                            Country = "New Zealand",
                            Description = "Museum of New Zealand.",
                            IsActive = true,
                            Name = "Te Papa Tongarewa",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 27,
                            Address = "Calle Alfonso XII 68",
                            City = "Madrid",
                            ClosingTime = new TimeSpan(0, 15, 0, 0, 0),
                            Country = "Spain",
                            Description = "Anthropology museum.",
                            IsActive = true,
                            Name = "National Museum of Anthropology",
                            OpeningTime = new TimeSpan(0, 9, 30, 0, 0),
                            Type = "Anthropology"
                        },
                        new
                        {
                            MuseumId = 28,
                            Address = "500 Harris St",
                            City = "Sydney",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "Australia",
                            Description = "Science and design museum.",
                            IsActive = true,
                            Name = "Powerhouse Museum",
                            OpeningTime = new TimeSpan(0, 10, 0, 0, 0),
                            Type = "Science"
                        },
                        new
                        {
                            MuseumId = 29,
                            Address = "Northern Parkway Rd",
                            City = "Johannesburg",
                            ClosingTime = new TimeSpan(0, 17, 0, 0, 0),
                            Country = "South Africa",
                            Description = "History of apartheid in South Africa.",
                            IsActive = true,
                            Name = "Apartheid Museum",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "History"
                        },
                        new
                        {
                            MuseumId = 30,
                            Address = "Corniche",
                            City = "Doha",
                            ClosingTime = new TimeSpan(0, 19, 0, 0, 0),
                            Country = "Qatar",
                            Description = "Islamic art collection.",
                            IsActive = true,
                            Name = "Museum of Islamic Art",
                            OpeningTime = new TimeSpan(0, 9, 0, 0, 0),
                            Type = "Art"
                        });
                });

            modelBuilder.Entity("TestProj.Models.OrderItemModel", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("MuseumId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestProj.Models.TicketTypeModel", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MuseumId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketTypeId");

                    b.HasIndex("MuseumId");

                    b.ToTable("TicketTypes");

                    b.HasData(
                        new
                        {
                            TicketTypeId = 1,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Adult",
                            Price = 25m
                        },
                        new
                        {
                            TicketTypeId = 2,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Student",
                            Price = 15m
                        },
                        new
                        {
                            TicketTypeId = 3,
                            IsActive = true,
                            MuseumId = 1,
                            Name = "Child",
                            Price = 10m
                        },
                        new
                        {
                            TicketTypeId = 4,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 5,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 6,
                            IsActive = true,
                            MuseumId = 2,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 7,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Adult",
                            Price = 28m
                        },
                        new
                        {
                            TicketTypeId = 8,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Student",
                            Price = 18m
                        },
                        new
                        {
                            TicketTypeId = 9,
                            IsActive = true,
                            MuseumId = 3,
                            Name = "Child",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 10,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Adult",
                            Price = 30m
                        },
                        new
                        {
                            TicketTypeId = 11,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Student",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 12,
                            IsActive = true,
                            MuseumId = 4,
                            Name = "Child",
                            Price = 15m
                        },
                        new
                        {
                            TicketTypeId = 13,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Adult",
                            Price = 22m
                        },
                        new
                        {
                            TicketTypeId = 14,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Student",
                            Price = 14m
                        },
                        new
                        {
                            TicketTypeId = 15,
                            IsActive = true,
                            MuseumId = 5,
                            Name = "Child",
                            Price = 9m
                        },
                        new
                        {
                            TicketTypeId = 16,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 17,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 18,
                            IsActive = true,
                            MuseumId = 6,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 19,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 20,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 21,
                            IsActive = true,
                            MuseumId = 7,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 22,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 23,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 24,
                            IsActive = true,
                            MuseumId = 8,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 25,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 26,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 27,
                            IsActive = true,
                            MuseumId = 9,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 28,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 29,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 30,
                            IsActive = true,
                            MuseumId = 10,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 31,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 32,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 33,
                            IsActive = true,
                            MuseumId = 11,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 34,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 35,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 36,
                            IsActive = true,
                            MuseumId = 12,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 37,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 38,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 39,
                            IsActive = true,
                            MuseumId = 13,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 40,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 41,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 42,
                            IsActive = true,
                            MuseumId = 14,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 43,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 44,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 45,
                            IsActive = true,
                            MuseumId = 15,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 46,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 47,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 48,
                            IsActive = true,
                            MuseumId = 16,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 49,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 50,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 51,
                            IsActive = true,
                            MuseumId = 17,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 52,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 53,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 54,
                            IsActive = true,
                            MuseumId = 18,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 55,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 56,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 57,
                            IsActive = true,
                            MuseumId = 19,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 58,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 59,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 60,
                            IsActive = true,
                            MuseumId = 20,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 61,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 62,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 63,
                            IsActive = true,
                            MuseumId = 21,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 64,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 65,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 66,
                            IsActive = true,
                            MuseumId = 22,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 67,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 68,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 69,
                            IsActive = true,
                            MuseumId = 23,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 70,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 71,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 72,
                            IsActive = true,
                            MuseumId = 24,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 73,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 74,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 75,
                            IsActive = true,
                            MuseumId = 25,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 76,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 77,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 78,
                            IsActive = true,
                            MuseumId = 26,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 79,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 80,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 81,
                            IsActive = true,
                            MuseumId = 27,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 82,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 83,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 84,
                            IsActive = true,
                            MuseumId = 28,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 85,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 86,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 87,
                            IsActive = true,
                            MuseumId = 29,
                            Name = "Child",
                            Price = 8m
                        },
                        new
                        {
                            TicketTypeId = 88,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Adult",
                            Price = 20m
                        },
                        new
                        {
                            TicketTypeId = 89,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Student",
                            Price = 12m
                        },
                        new
                        {
                            TicketTypeId = 90,
                            IsActive = true,
                            MuseumId = 30,
                            Name = "Child",
                            Price = 8m
                        });
                });

            modelBuilder.Entity("TestProj.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TestProj.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProj.Models.MuseumEmployeeModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Employees")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", "User")
                        .WithOne("MuseumEmployee")
                        .HasForeignKey("TestProj.Models.MuseumEmployeeModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestProj.Models.MuseumImageModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Images")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("TestProj.Models.OrderItemModel", b =>
                {
                    b.HasOne("TestProj.Models.OrderModel", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProj.Models.TicketTypeModel", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("Orders")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TestProj.Models.UserModel", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestProj.Models.TicketTypeModel", b =>
                {
                    b.HasOne("TestProj.Models.MuseumModel", "Museum")
                        .WithMany("TicketTypes")
                        .HasForeignKey("MuseumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Museum");
                });

            modelBuilder.Entity("TestProj.Models.MuseumModel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Images");

                    b.Navigation("Orders");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("TestProj.Models.OrderModel", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TestProj.Models.UserModel", b =>
                {
                    b.Navigation("MuseumEmployee");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
